# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NuGet Pack & Push

on:
  push:
    tags:
      - 'v*.*.*'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet pack -c Release --no-restore src/TG.MathEx/TG.MathEx.csproj
    
    - name: Push to NuGet.org
      run: dotnet nuget push src/TG.MathEx/bin/Release/TG.MathEx.*.nupkg --api-key "$NUGET_TOKEN" --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}

    - name: Push symbol package to NuGet.org
      run: dotnet nuget push src/TG.MathEx/bin/Release/TG.MathEx.*.snupkg --api-key "$NUGET_TOKEN" --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
